image: node:20

pages:
  stage: deploy
  script:
    - cd frontend
    - npm ci
    - npm run build
    - cd ..
    - rm -rf public_pages
    - mv frontend/dist public
  artifacts:
    paths:
      - public
  only:
    - main
    - master
